# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: app
#   labels:
#     provider: app
#     environ: prod
# spec:
#   ports:
#   - port: 80
#     # targetPort: 5000
#   selector:
#     provider: app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  labels:
    provider: app
    environ: prod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        provider: app
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
          - key: config
            path: nginx.conf
      containers:
      - name: nginx-proxy
        image:  nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/
          name: nginx-config
      - name: 12factor
        image: alainchiasson/12factor
        env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: database.host
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: database.user
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: database.password
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: database.name
        ports:
        - containerPort: 5000
