---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    provider: app
    environ: prod
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    provider: app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  labels:
    provider: app
    environ: prod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        provider: app
    spec:
      containers:
      - name: 12factor
        image: alainchiasson/12factor
        env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: database.host
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: database.user
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: database.password
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: database.name
        ports:
        - containerPort: 5000
