---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    service: mysql
    environ: dev
    version: '1'
spec:
  ports:
  - port: 3306
  selector:
    provider: mysql
    environ: dev
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    provider: mysql
    environ: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        provider: mysql
        environ: dev
        test: replication
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: database.password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: database.name
        ports:
        - containerPort: 3306
