---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    provider: mysql
    heritage: none
spec:
  ports:
  - port: 3306
  selector:
    provider: mysql
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  labels:
    provider: mysql
    heritage: none
spec:
  replicas: 1
  template:
    metadata:
      labels:
        provider: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ${DATABASE_PASSWORD}
        - name: MYSQL_DATABASE
          value: ${MYSQL_DATABASE}
        ports:
        - containerPort: 3306
