---
apiVersion: v1
kind: Pod
metadata:
  name: dbinit
  labels:
    provider: dbinit
    heritage: none
spec:
  restartPolicy: Never
  containers:
  - name: 12factor-dbinit
    image: alainchiasson/12factor-dbinit
    env:
    - name: DATABASE_HOST
      value: ${DATABASE_HOST}
    - name: DATABASE_USER
      value: ${DATABASE_USER}
    - name: DATABASE_PASSWORD
      value: ${DATABASE_PASSWORD}
    - name: DATABASE_NAME
      value: ${DATABASE_NAME}
    - name: DATABASE_URL
      value: ${DATABASE_URL}
    - name: MYSQL_ROOT_PASSWORD
      value: ${DATABASE_PASSWORD}
    - name: MYSQL_DATABASE
      value: ${MYSQL_DATABASE}
