kind: ConfigMap
apiVersion: v1
metadata:
  name: db-config
data:
  database.host: mysql
  database.user: root
  database.password: mytest
  database.name: 12factor


# export DATABASE_HOST=mysql
# export DATABASE_USER=root
# export DATABASE_PASSWORD=mytest
# export DATABASE_NAME=12factor
#
# # For Mysql Docker image
# export MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
# export MYSQL_DATABASE=${DATABASE_NAME}
#
# # Using SQL Alchemy - how can I move the password out of this ?
# export DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}/${DATABASE_NAME}
