---
apiVersion: v1
data:
  database.host: mysql
  database.user: root
  database.password: mytest
  database.name: 12factor
kind: ConfigMap
metadata:
  name: db-config
---
apiVersion: v1
data:
  config: |
    error_log /dev/stdout info;
    events {
        worker_connections 1024;
    }

    http {
      server {
        listen *:80;

        location /users {
          proxy_pass http://localhost:5000/version;
        }
      }
    }
kind: ConfigMap
metadata:
  name: nginx-config
